### PR TITLE
Added admin portal w/ moderation functionality, comment flagging MVP, and comment tests

### PR DESCRIPTION
**Pull request by Bwillia2**
**Description:**
This PR adds the MVP for #11 (removing comments as admin), #25 (admin portal), #17 (flagging comments as user), and #41 unit tests for comments and their moderation  

**1. Added Moderation Features:**
- users can flag/ unflag comment (#51)
- "flagCount" column added to comment model (#50)
- flag model created in the backend
- admins can access dedicated portal to view activity feed
- admins can see all comments of post
- admins can see how many flags each comment has (#52)
- admins can hide/ unhide any comments
- users will see “this post has been removed because its against community guidelines” in the comment text when it's hidden 

**2. Added Comment Testing**
- unit tests written for loading and creating comments

**3. Added Moderation Testing**
- unit tests written for flagging/unflagging comments
- unit tests written for hiding/unhiding comments

**4. Known Bugs:**
- N/A

**5. Future Needs:**
- make flags feel more serious or put it behind ellipses (#68)
- toggle option for admin portal to show only flagged comments
- tooltips: hover over flag and say 'this flags a comment' or for likes 'this likes the post' (#69)

### CODE REVIEW

**Comment by tylowe-labs** [comment]
@Bwillia2 @Jareltey for this bug "after flagging/unflagging, the thread will auto-scroll to the top," I'm pretty sure that using trackby will solve the issue (reloading/rendering all the comments) after you flag it

**Comment by tylowe-labs** [comment]
@Bwillia2 @Jareltey for this bug "after flagging, closing modal, and opening modal, comment will appear unflagged even though it is flagged in the backend. Trying to flag it will trigger "Error: User has already flagged this comment" it is less so a bug, more state management. the comments modal has a different set of comments for the post than the activity feed has. a solution to this is to pass back the list of comments on modal close and then reassign the feed item's comments so that it matches what it was after comment modal closed

**Review by tylowe-labs — COMMENTED** [review]
see comments above ^ also having in its current state having a tooltip is a need not a consideration. also, consider writing tests as you develop as they should (at least some amount of them) be part of this commit

**Review by tylowe-labs — APPROVED** [review]
looks good but there are a lot of conflicts to resolve, please be careful with that!

**Review by AlexanderChiuy — APPROVED** [review]

**Pull request merged**
