### PR TITLE
redirect activity post project link tothe project cover page

### LINKED ISSUE #77: @frontend: add a modal to activity feed that shows project cover page
Currently, the Activity Feed information button next to the Project Title of posts has a placeholder destination (CM profile) but it should change to the relevant project cover page.

Located in: iMPublic/libs/client/shell/src/lib/projects/project-cover-page/project-cover-page.component.html

Needs to be linked to the activityfeed frontend button (information button next to the project title that shows project cover page)

### PR DESCRIPTION
**Pull request by AlexanderChiuy**
Resolves #77

### CODE REVIEW

**Comment by AlexanderChiuy** [comment]
image

**Review by isong2 — DISMISSED** [review]
Looks good!

Didn't realize that project ID was already a field in the backend, sorry about that!

**Review by isong2 — CHANGES_REQUESTED** [review]
Could you include what happens when you hit the back arrow in the demo?

Does it take you back to the Activity Feed spot that you were just at ?

Maybe it makes more sense for it to be its own modal rather than routing to the projects page if that isn't the case.

**Comment by AlexanderChiuy** [comment]
The back button works as expected. I think routing to the project cover page makes the most sense because there is a lot of state attached t this component which we would need to pass in. By just routing to the page, we only need to pass in the projectId

**Comment by tylowe-labs** [comment]
> The back button works as expected. I think routing to the project cover page makes the most sense because there is a lot of state attached t this component which we would need to pass in. By just routing to the page, we only need to pass in the projectId

@AlexanderChiuy as long as the back button puts you back on the feed where you left off we are good

**Review by tylowe-labs — APPROVED** [review]
thanks for this update Alex

**Pull request merged**
