### PR TITLE
Make admin moderation hifi + enable toggling between all/flagged posts

### LINKED ISSUE #81: Add toggling between all posts or posts with flagged comments to admin page
Enable 2 modes in admin moderation page:
1. See all posts
2. See only posts with flagged comments

### PR DESCRIPTION
**Pull request by Jareltey**
Resolves #81 (toggling between all/flagged posts)

Features added:
- Disabled like button in admin moderation panel
- Replace "Refresh" button with toggling button at upper right of moderation panel
- Saving state (hidden/unhidden comments) when toggling
- Add "Comment Moderation" as a menu item with "comments" icon

(Toggling between all/flagged)

https://user-images.githubusercontent.com/62992282/234720796-c1ebbed6-5b50-4e0a-926d-1aeefeb30131.mov

(Saving state when toggling)

https://user-images.githubusercontent.com/62992282/234720903-7b024abc-640f-4a68-af8c-f15250ae6455.mov

Known bugs:
N/A

### CODE REVIEW

**Review by tylowe-labs — COMMENTED** [review]
@Jareltey From looking at this code I believe it is accurate that these filterings are only done at a Frontend level and not backend, correct?

**Review by AlexanderChiuy — APPROVED** [review]

**Comment by AlexanderChiuy** [comment]
> @Jareltey From looking at this code I believe it is accurate that these filterings are only done at a Frontend level and not backend, correct?

I think this is fine because it'll be faster than querying the database again.

**Comment by Jareltey** [comment]
> @Jareltey From looking at this code I believe it is accurate that these filterings are only done at a Frontend level and not backend, correct?

When toggling from all posts to flagged posts, the posts are being filtered on the frontend. When toggling from flagged posts to all posts, the easiest way I could think of doing this is to do an ngInit() call to fetch all the posts again, so in that sense there is a database query involved.

**Comment by tylowe-labs** [comment]
> > @Jareltey From looking at this code I believe it is accurate that these filterings are only done at a Frontend level and not backend, correct?
> 
> When toggling from all posts to flagged posts, the posts are being filtered on the frontend. When toggling from flagged posts to all posts, the easiest way I could think of doing this is to do an ngInit() call to fetch all the posts again, so in that sense there is a database query involved.

@Jareltey you could probably just do this in the toggle button function  `this.updateState{ posts: <update posts so only flagged > }`

**Pull request merged**
